# Generated by Django 3.2.6 on 2021-08-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones_Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuota', models.IntegerField()),
                ('Fecha_Pago', models.DateField()),
                ('Num_recibo', models.IntegerField()),
                ('Monto', models.FloatField()),
                ('Capital', models.FloatField()),
                ('Intereses', models.FloatField()),
                ('Saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos_prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prestamo', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha_otorgado', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('plazo_meses', models.IntegerField()),
                ('taza_mensual', models.FloatField()),
                ('Periodo_Gracia', models.IntegerField()),
                ('Taza_Descuento', models.FloatField()),
                ('Monto', models.FloatField()),
                ('Recargos_mora', models.FloatField()),
            ],
        ),
    ]
