# Generated by Django 3.2.6 on 2021-09-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_acciones_prestamos',
            name='Usuario',
            field=models.CharField(default='s', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_datos_prestamos',
            name='Usuario',
            field=models.CharField(default='s', max_length=15),
            preserve_default=False,
        ),
    ]
