# Generated by Django 3.2.6 on 2021-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Acciones_Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prestamo', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha_otorgado', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('plazo_meses', models.IntegerField()),
                ('taza_mensual', models.FloatField()),
                ('Periodo_Gracia', models.IntegerField()),
                ('Taza_Descuento', models.FloatField()),
                ('Monto', models.FloatField()),
                ('Recargos_mora', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Datos_prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prestamo', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha_otorgado', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('plazo_meses', models.IntegerField()),
                ('taza_mensual', models.FloatField()),
                ('Periodo_Gracia', models.IntegerField()),
                ('Taza_Descuento', models.FloatField()),
                ('Monto', models.FloatField()),
                ('Recargos_mora', models.FloatField()),
            ],
        ),
    ]
