# Generated by Django 3.2.6 on 2021-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_auto_20210919_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_prestamos',
            name='miembro',
            field=models.CharField(default='n', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_datos_prestamos',
            name='miembro',
            field=models.CharField(default='n', max_length=1),
            preserve_default=False,
        ),
    ]
