# Generated by Django 3.2.6 on 2021-08-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_auto_20210810_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_datos_prestamos',
            name='id_prestamo',
        ),
        migrations.AddField(
            model_name='temp_datos_prestamos',
            name='id_persona',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
