# Generated by Django 3.2.6 on 2021-08-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_auto_20210810_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_datos_prestamos',
            name='Intereses',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
