# Generated by Django 3.2.6 on 2021-08-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_temp_datos_prestamos_intereses'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones_prestamos',
            name='id_prestamo',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
