# Generated by Django 3.2.6 on 2021-08-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_acciones_prestamos_id_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_prestamos',
            name='id_cliente',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
