# Generated by Django 3.2.6 on 2021-08-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_datos_prestamos_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_prestamos',
            name='id_cliente',
            field=models.CharField(max_length=15),
        ),
    ]
