# Generated by Django 3.2.6 on 2021-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_variables_generales'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones_prestamos',
            name='Pago',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
