# Generated by Django 3.2.6 on 2021-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_acciones_prestamos_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones_prestamos',
            name='Descuento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_acciones_prestamos',
            name='Descuento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
