# Generated by Django 3.2.6 on 2021-08-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_auto_20210818_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones_prestamos',
            name='Saldo_mora',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
