# Generated by Django 3.2.6 on 2021-08-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_acciones_prestamos_saldo_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones_prestamos',
            name='Intereses_moratorios',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
