# Generated by Django 3.2.6 on 2021-08-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_datos_acciones_ahorro',
            name='usuario',
            field=models.CharField(default='nada', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_datos_ahorrante',
            name='usuario',
            field=models.CharField(default='nada', max_length=15),
            preserve_default=False,
        ),
    ]
