# Generated by Django 3.2.6 on 2021-09-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro_Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('Debe', models.FloatField()),
                ('Haber', models.FloatField()),
                ('Cuadre', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuenta', models.CharField(max_length=50)),
                ('Debe', models.FloatField()),
                ('Haber', models.FloatField()),
                ('Fecha', models.DateField()),
                ('Cuadre', models.FloatField()),
            ],
        ),
    ]
