# Generated by Django 3.2.6 on 2021-09-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro_diario',
            name='Usuario',
            field=models.CharField(default='s', max_length=20),
            preserve_default=False,
        ),
    ]
