# Generated by Django 3.2.6 on 2021-09-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_libro_diario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro_diario',
            name='Debe',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='libro_diario',
            name='Haber',
            field=models.CharField(max_length=150),
        ),
    ]
