# Generated by Django 3.2.6 on 2021-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_libro_mayor_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuenta', models.CharField(max_length=50)),
                ('Saldo', models.FloatField()),
                ('Activo', models.FloatField()),
                ('Pasivo', models.FloatField()),
            ],
        ),
    ]
