# Generated by Django 3.2.6 on 2021-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_balance_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_general',
            name='Total',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
