# Generated by Django 3.2.6 on 2021-10-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_balance_general_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuenta', models.CharField(max_length=50)),
                ('Fecha_1', models.FloatField()),
                ('Fecha_2', models.FloatField()),
                ('Saldo', models.FloatField()),
                ('Rojo', models.FloatField()),
                ('Amarillo', models.FloatField()),
                ('Verde', models.FloatField()),
            ],
        ),
    ]
