# Generated by Django 3.2.6 on 2021-08-31 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_caja',
            name='Fecha',
            field=models.DateField(default=datetime.date(2021, 8, 31)),
        ),
    ]
