# Generated by Django 3.2.6 on 2021-09-19 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_temp_caja_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_caja',
            name='Fecha',
            field=models.DateField(default=datetime.datetime(2021, 9, 19, 1, 40, 54, 560799, tzinfo=utc)),
        ),
    ]
