# Generated by Django 3.2.6 on 2021-08-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones_accionista',
            name='Identidad',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_acciones_accionista',
            name='Identidad',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
